# Generated by Django 3.1.7 on 2021-03-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topper',
            old_name='topper_category',
            new_name='topper_std',
        ),
    ]
