# Generated by Django 3.1.7 on 2021-03-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210330_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentassignment',
            name='status',
        ),
        migrations.AlterField(
            model_name='sentassignment',
            name='image',
            field=models.FileField(upload_to='assignment/'),
        ),
        migrations.RemoveField(
            model_name='sentassignment',
            name='name',
        ),
        migrations.AddField(
            model_name='sentassignment',
            name='name',
            field=models.ForeignKey(default=232, on_delete=django.db.models.deletion.CASCADE, to='teacher.studentprofile'),
        ),
    ]
