# Generated by Django 3.1.7 on 2021-03-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210331_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentassignment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.studentprofile'),
        ),
    ]
